## Experiment 11 EDA 18/03/2026
### Name : Drishti Heda
### PRN : 25070123045
### Batch : EnTC A3
### Title: Categorical Data Analysis using Python

In [1]:
import pandas as pd
import numpy as np
df1= pd.DataFrame({'C1': [11,21, np.nan], 'C2': [15, np.nan, np.nan], 'C3': [10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [3]:
df1.isna () #Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [4]:
df1.notna ()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [5]:
df1.isna().sum() #column wise na values

C1    1
C2    2
C3    0
dtype: int64

In [6]:
df1.dropna() #NaN rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [7]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [8]:
df1.fillna(value='default')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  default  20
2  default  default  30

In [9]:
df1.fillna(df1.mean()) #mean values of columns

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [10]:
#Preprocessing on a dataset-1
import pandas as pd
data = {
"Roll No": [45,47,54,55,58],
"Name": ["Drishti", "Falak", "Hiranya", "Jahnvi", "Jayvee"],
"Age": [18, "-", 19, 21, "20"],
"Marks": [ 85,75,89,92,90],
"Department": ["CSE", "IT", "ENTC", "cse", "CSE"],
"Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}
df = pd.DataFrame(data)
# Save as CSV
df.to_csv("student_data.csv", index= False)

In [11]:
import pandas as pd
import numpy as np
#Step 1: Load the Dataset
df= pd.read_csv("student_data.csv")
print("Original Data: ")
print(df)

Original Data:
   Roll No     Name Age  Marks Department Admission_Date
0       45  Drishti  18     85        CSE     01-06-2023
1       47    Falak   -     75         IT     03-06-2023
2       54  Hiranya  19     89       ENTC     05-06-2023
3       55   Jahnvi  21     92        cse     07-06-2023
4       58   Jayvee  20     90        CSE       10/06/23

In [12]:
#Step 2: Replace "-" with NaN to mark missing values
df.replace("-", np.nan, inplace=True)
#Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
'''When converting data (like strings to datatime),
if some values are invalid or cannot be converted,
instead of throwing an error, it will:
Replace those invalid values with NaT(Not a Time)'''
df

   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     01-06-2023
1       47    Falak   NaN     75         IT     03-06-2023
2       54  Hiranya  19.0     89       ENTC     05-06-2023
3       55   Jahnvi  21.0     92        cse     07-06-2023
4       58   Jayvee  20.0     90        CSE       10/06/23

In [13]:
#Step 3: Check missing values
print("\nMissing Values: ")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [2]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

NameError: name 'df' is not defined