## EDA Experiment- 12 Date- 18/03/2026
## Topic- Data Preprocessing and Handling Missing Values in Python
## Name- Drishti Heda
## PRN-25070123045
## ENTC A3

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1': [11,21, np.nan],'C2': [15, np.nan, np.nan], 'C3': [10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:

df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:

df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
df1.fillna(df1.mean())

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [2]:
#Preprocessing on a dataset-1
import pandas as pd
data = {
"Roll No": [45,47,54,55,58],
"Name": ["Drishti", "Falak", "Hiranya", "Jahnvi", "Jayvee"],
"Age": [18, "-", 19, 21, "20"],
"Marks": [ 85,75,89,92,90],
"Department": ["CSE", "IT", "ENTC", "cse", "CSE"],
"Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}
df = pd.DataFrame(data)
# Save as CSV
df.to_csv("student_data.csv", index= False)

In [3]:
import pandas as pd
import numpy as np
#Step 1: Load the Dataset
df= pd.read_csv("student_data.csv")
print("Original Data: ")
print(df)

Original Data:
   Roll No     Name Age  Marks Department Admission_Date
0       45  Drishti  18     85        CSE     01-06-2023
1       47    Falak   -     75         IT     03-06-2023
2       54  Hiranya  19     89       ENTC     05-06-2023
3       55   Jahnvi  21     92        cse     07-06-2023
4       58   Jayvee  20     90        CSE       10/06/23

In [4]:
df.replace("-", np.nan, inplace=True)
df

   Roll No     Name  Age  Marks Department Admission_Date
0       45  Drishti   18     85        CSE     01-06-2023
1       47    Falak  NaN     75         IT     03-06-2023
2       54  Hiranya   19     89       ENTC     05-06-2023
3       55   Jahnvi   21     92        cse     07-06-2023
4       58   Jayvee   20     90        CSE       10/06/23

In [5]:
#Step 2: Replace "-" with NaN to mark missing values
df.replace("-", np.nan, inplace=True)
#Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
'''When converting data (like strings to datatime),
if some values are invalid or cannot be converted,
instead of throwing an error, it will:
Replace those invalid values with NaT(Not a Time)'''
df

   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     01-06-2023
1       47    Falak   NaN     75         IT     03-06-2023
2       54  Hiranya  19.0     89       ENTC     05-06-2023
3       55   Jahnvi  21.0     92        cse     07-06-2023
4       58   Jayvee  20.0     90        CSE       10/06/23

In [6]:
#Step 3: Check missing values
print("\nMissing Values: ")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [9]:
# Fill missing Age with mean

df["Age"].fillna(df["Age"].mean(), inplace=True)
df

/tmp/ipykernel_27574/261067492.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     01-06-2023
1       47    Falak  19.5     75         IT     03-06-2023
2       54  Hiranya  19.0     89       ENTC     05-06-2023
3       55   Jahnvi  21.0     92        cse     07-06-2023
4       58   Jayvee  20.0     90        CSE       10/06/23

In [ ]:
df["Marks"].fillna(df["Marks"].mean(), inplace=True)
df

/tmp/ipykernel_211/1415366611.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(), inplace=True)

   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     01-06-2023
1       47    Falak  19.5     75         IT     03-06-2023
2       54  Hiranya  19.0     89       ENTC     05-06-2023
3       55   Jahnvi  21.0     92        cse     07-06-2023
4       58   Jayvee  20.0     90        CSE       10/06/23

In [ ]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Step 5: Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()
df

   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     01-06-2023
1       47    Falak  19.5     75         IT     03-06-2023
2       54  Hiranya  19.0     89       ENTC     05-06-2023
3       55   Jahnvi  21.0     92        CSE     07-06-2023
4       58   Jayvee  20.0     90        CSE       10/06/23

In [ ]:
#Step 6: Convert Admission_Data to standard datatime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')

In [ ]:
# Step 7: Show Cleaned Data
print("\nCleaned Data:")
print(df)

Cleaned Data:
   Roll No     Name   Age  Marks Department Admission_Date
0       45  Drishti  18.0     85        CSE     2023-01-06
1       47    Falak  19.5     75         IT     2023-03-06
2       54  Hiranya  19.0     89       ENTC     2023-05-06
3       55   Jahnvi  21.0     92        CSE     2023-07-06
4       58   Jayvee  20.0     90        CSE            NaT

In [ ]:
# Step 8: Save cleaned dataset
df.to_csv("cleaned_student_data.csv", index=False)

print("\nCleaned CSV File saved")

Cleaned CSV File saved

In [ ]:

# Working with missing values on DataSet-2

df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum() #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
#Inputing the Missing Value

#1. Luggage.Room
df ['Luggage.room'] = df['Luggage.room'].fillna(value=df['Luggage.room'].mean())

In [ ]:
#2. Rear.seat.room
df ['Rear.seat.room'] =df ['Rear.seat.room'].fillna(value=df ['Rear.seat.room'].mean())

In [ ]:

#3. AirBags
df ['AirBags'] =df ['AirBags'].fillna(value=df ['AirBags'].mode().values[0])

In [ ]:

df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
# Saved cleaned dataset
df.to_csv("Cleaned_Cars93.csv", index=False)